spring:
  main:
    banner-mode: off

  web:
    resources:
      static-locations:
        - classpath:/static/
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /${path}

  port: ${port:8080}

game:
  move-time: ${moveTime:120}
